### ISSUE TITLE
VT shows a few positives

### ISSUE THREAD

**Issue by tyeeman** [srackham/hindsite#3]
My favorite SSG! Just downloaded the latest (thanks) and it shows a few positives. Does it really matter?

**Comment by srackham** [comment]
Thanks for the feedback. What do you mean by "a few positives"?

**Comment by tyeeman** [comment]
Virus Total found a few supposed infections but we know they are false positives - I wouldn't worry about it.

https://www.virustotal.com/gui/file/c522e487ed34460e3d9b644072dc48b292d7133f91597bb385e0508396dc4a37/detection
