### ISSUE TITLE
keep option question

### ISSUE THREAD

**Issue by tyeeman** [srackham/hindsite#5]
Thanks for the update.  

Please confirm the following are true using the -keep option 

The build dir is not deleted, so any folders/files in there that are not in the content dir are left untouched? 

Files in the content dir will overwrite current files in the build dir? 

If I want to delete files in the build dir that are not in the content dir, I must do it manually?

**Comment by srackham** [comment]
The `-keep` inhibits the deletion of build directory contents prior to a full site
rebuild by thebuild and serve commands. The build directory is not deleted, just
the files and folder contained in the build directory. `-keep` has no effect on
the content and template directories. Updates to
generated files in the build directory will overwrite existing files same-named
in the build directory.

If you don't specify `-keep` then all files in the build directory are deleted
prior to the build, this is the default behaviour and it ensures a clean build
i.e. any files that are no longer built will no longer be in the build
directory.

The purpose of the `-keep` option is to allow the creation of compound websites
(websites built from multiple Hindsite sites), for example the Hindsite
documentation website contains the documentation site plus the build-in template
sites.
