### ISSUE TITLE
AWS Amplify problem

### ISSUE THREAD

**Issue by tyeeman** [srackham/hindsite#6]
I'm experimenting with Amazon's free static site options and have run across a url problem. It rewrites URLs ending in folder/filename. html. If it sees that, it makes a pretty url out of it as folder/filename/. This means there has to be an index.html file in a folder called filename, which obviously does not exist. Does hindsite have any option to build all pages/posts as an index file in a folder?

Example - my .md file is /folder1/folder2/info.md. Build it as /folder1/folder2/info/index.html.

**Comment by srackham** [comment]
Yes, see https://srackham.github.io/hindsite/index.html#build-paths and https://srackham.github.io/hindsite/index.html#permalink
